id:                             ViT
pretrained:                     Null
model:
    name:                       BaseTimmModel
    args:
        name:                   vit_base_patch16_224
        num_classes:            5
        freeze_backbone:        False
optimizer:
    name:                       Adam
    args:
        lr:                     0.0001
loss:
    name:                       FocalLoss
    args:                       Null
metric:
    -   name:                   Accuracy
        args:                   Null
scheduler:
    name:                       StepLR
    args:
        step_size:              2
        gamma:                  0.2
        last_epoch:             -1  
dataset:
    train:
        name:                   LeafDataset
        args:
            data_dir:           data/train_images/         
            csv_path:           lists/train.csv
            IMG_SIZE:           224
            is_train:           True  
        loader:
            name: DataLoader
            args:
                batch_size:     128
                shuffle:        True
                drop_last:      True 
    val:
        name:                   LeafDataset
        args:
            data_dir:           data/train_images/         
            csv_path:           lists/val.csv
            IMG_SIZE:           224
            is_train:           False  
        loader:
            name: DataLoader
            args:
                batch_size:     32
                shuffle:        True

trainer: 
    nepochs: 10
    val_step: 1
    log_step: 1