id:                             ViTCosine
pretrained:                     Null
model:
    name:                       BaseTimmModel
    args:
        name:                   vit_base_patch16_224
        num_classes:            5
        freeze_backbone:        False
optimizer:
    name:                       SGD
    args:
        lr:                     0.03 
        momentum:               0.9
        weight_decay:           0
loss:
    name:                       FocalLoss
    args:                       Null
metric:
    -   name:                   Accuracy
        args:                   Null
scheduler:
    name:                       WarmupCosineSchedule
    args:
        warmup_steps:           100
        t_total:                3000
dataset:
    train:
        name:                   LeafDataset
        args:
            data_dir:           data/train_images/         
            csv_path:           lists/train.csv
            IMG_SIZE:           224
            is_train:           True  
        loader:
            name: DataLoader
            args:
                batch_size:     2
                shuffle:        True
                drop_last:      True 
    val:
        name:                   LeafDataset
        args:
            data_dir:           data/train_images/         
            csv_path:           lists/val.csv
            IMG_SIZE:           224
            is_train:           False  
        loader:
            name: DataLoader
            args:
                batch_size:     2
                shuffle:        True

trainer: 
    nepochs: 10
    val_step: 1
    log_step: 1